# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'StressDetectionKit' do
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  pod 'RNSensors', :path => '../node_modules/react-native-sensors'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'ART',
  ]
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end